In [39]:
### NumPy (Numerical Python) is the fundamental, open-source library for scientific computing in Python, 
# providing support for large, high-performance, multi-dimensional arrays (called ndarray objects) and 
# a vast collection of mathematical functions to operate on these arrays efficiently. 
# It is a core component of the Python data science ecosystem, serving as the foundation for 
# libraries like Pandas, SciPy, and Scikit-learn.
# 

import numpy as np

## Create arryas using numpy
arr1 = np.array([2,4,6,8,10])               ## Create 1D array
print(arr1)
print(type(arr1))
print(arr1.shape)        ## Output: (5,) meaning 1 dimentional array with five elements
arr1.reshape(1,5)        ## We can convert it to 2D as 1 row and 5 cols. result : array([[ 2,  4,  6,  8, 10]])

#another example
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.shape)

# Some other ways to create arrays
arr3 = np.arange(0,10,2)
print(arr3)
print(arr3.shape)
arr3.reshape(5,1)
print(arr3.reshape(5,1))


## some in=built functions in numpy
np.ones((3,4))

## identity matrix - diagonal elements are 1
np.eye(3)           


## Attributes of numpy array
arr4 = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr4)
print("Shape:", arr4.shape)        # Output: (2, 3)
print("Number of dimensions:", arr4.ndim)   # Output: 2
print("Size (number of elements):", arr4.size)   # Output: 6
print("Data type:", arr4.dtype)    # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr4.itemsize)   # Output: 8 (may vary based on platform)

## Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise additon
print("Additon: ", arr1+arr2)

## Element wise subtraction
print("Subtraction: ", arr1-arr2)

## Element wise multiplication
print("Multiplication: ", arr1*arr2)

## Element wise division
print("Divison: ", arr1/arr2)

##------------------------------------------------------------------
## Universal functions - the functions that apply to entire array
##------------------------------------------------------------------
arr5 = np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr5))
## exponential
print(np.exp(arr5))

## Sine
print(np.sin(arr5))

## Natural logs
print(np.log(arr5))

##------------------------------------------------------------------
## Array Slicing and Indexing
##------------------------------------------------------------------
arr6 = np.array( [[1,2,3,4], [5,6,7,8], [9,10,11,12]] )
print("Array: \n", arr6)
'''
Output:
Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
'''

print(arr6[0][0])
## output : 1
print(arr6[1:])  ## print 2nd row (i.e. index 1) till last row
print(arr6[1:, 2:])  ## print 2nd row (i.e. index 1) till last row and 3rd column onwards to last column i.e. (index 2 onwards) 
'''
Output:
[[ 7  8]
 [11 12]]
'''
print(arr6[0:2, 1:])
'''
Output
[[2 3 4]
 [6 7 8]]
'''
print(arr6[1:, 1:3])
'''
Output:
[[ 6  7]
 [10 11]]
'''

##------------------------------------------------------------------
## Modify Array elements
##------------------------------------------------------------------
arr6[0,0] = 100
print(arr6)

arr6[1:] = 200 ## Replace all elements from row 2 onwards with 200
print(arr6)


##------------------------------------------------------------------
## Some practical applications of arrays
##------------------------------------------------------------------

### Statistical concepts: Normalization
# To have a mean of 0 and standard deviation
data = np.array([1,2,3,4,5])

# Calculate the mean and standard dev
mean = np.mean(data)
std_dev = np.std(data)

# Normalize data
normalized_data = (data - mean)/std_dev
print("Normalized data: ",normalized_data)

median = np.median(data)
print("Median: ", median)

variance = np.var(data)
print("Variance: ", variance)

##------------------------------------------------------------------
## Some logical operations on arrays
##------------------------------------------------------------------
data>3    # Output: array([False, False, False,  True,  True])

data[data>3]  # returns array with elements > 3: i.e. array([4, 5])
data[(data>3) & (data <5) ] 

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
[0 2 4 6 8]
(5,)
[[0]
 [2]
 [4]
 [6]
 [8]]
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8
Additon:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Divison:  [0.1 0.1 0.1 0.1 0.1]
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[2 3 4]
 [6 7 8]]
[[ 6  7]
 [10 11]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [200 200 200 200]
 [200 200 200 200]]
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Median:  3.0
Variance:  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()